spring:
  application:
    name: business-reg
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        #server-addr: local.k8s.node2:80
        server-addr: 192.168.56.101:8848
dubbo:
  scan:
    base-packages: com.jh.myshop.plus.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    #address: nacos://local.k8s.node2
    #port: 80
    address: nacos://192.168.56.101
    port: 8848
server:
  # ${random.int[9000,9999]} 随机端口
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"